### ISSUE TITLE
remux.py issue

### ISSUE THREAD

**Issue by Attila047** [pcroland/coub_likes_downloader#2]
joining doesn't work for me,
it starts but at the very first join it just hangs and when i stop the script it creates a huge video in the final folder (like 20gb if i wait for a few minutes and stop the script),
the file created looks like the video in an infinite loop and the whole music one time in the beginning,

i installed WSL, python3, ffmpeg
what could i have missed?

**Comment by pcroland** [comment]
included an argparser with a `--force-remux` option in the latest commit.
