### ISSUE TITLE
remux only does one video loop

### ISSUE THREAD

**Issue by Attila047** [pcroland/coub_likes_downloader#3]
thanks for the quick solution before,
i run `python3 coub.py -l -f` but the remuxed videos seem to only loop once, check the attached example
[https://streamable.com/wmwqfv](url)

can you please set it to loop for the duration of the whole song?

**Comment by ZwiebelTVDE** [comment]
Not sure if it's already fixed but I don't run in that problem. 
I downloaded my likes with and without remux and the duration of the mp3s match the duration of the remuxed mp4s.
Maybe try and clone the current version and try again

**Comment by pcroland** [comment]
This tool was intended to be used just for downloading coubs as they are stored for archiving purposes. On coub.com both the video and audio loops independently. I don't plan to add a feature for "fixing" it. If a coub has 10 seconds of video and 10 minutes of audio, looping the video in the container until the audio is finished would greatly increase the file size.
